### ISSUE TITLE
Sites

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#109]
change in the data structure for site, fields to be added:

site.displayProperties - an object to hold all random properties of the parent site that should be displayed to the volunteer
site.transectParts.displayProperties - ditto but for each segment/ child element, eg. habitat
site.adminProperties - an object to hold all random properties of the parent site that should be displayed to the admins only, e.g helcom
site.transectParts.adminProperties - ditto but for each segment/ child element
site.transectParts.otherCrs - an object to hold coordinates of the transect part but in EPSG other than 4326. Key should be the name of the coordinate system, value - the coordinates

**Comment by magdziarek** [comment]
e.g. in the migration scripts it's:
            "otherCRS": {
                "coords_3021":[pts_x_coord_3021, pts_y_coord_3021],
                "coords_3006":[pts_x_coord_3006, pts_y_coord_3006]
            },

**Comment by mathieuLU** [comment]
Ok so for my specific fiields:

For instance I need to specify for STD sites a field Fjall104 and Fjall142.
For nattrutt sites I'd like to store coordinates for the centroid in ther format (i guess a field like otherCRS)

=> I can use site.adminProperties right ?

i culdn't find any exemple. DO you have some ?
> db.site.find({adminProperties:{$exists:1}}).count()
0

**Comment by magdziarek** [comment]
An example would be with the inventory fields for transect parts in **standardrutt**. Have a look at: `db.site.find({"transectParts.adminProperties":` {$exists: true}}, {transectParts: 1}).pretty()

I haven't seen the need for site.adminProperties yet, only site.transectParts.adminProperties but now thinking about it, the start year of **nattrutterna** should probably be in there, like so:
`adminProperties: {startYear: 2000}`

Also - you suggested creating an edit page for admins that will have all fields of the site. I think those properties will mostly be needed on that page. I wanted adminProperties to store what needs to be displayed on the index page for admins only. Which I think shouldn't be too much...

**Comment by mathieuLU** [comment]
regarding the nattrutt sites, the one I create with only centroid. Where do you think I should put the other coordinates ?
My first idea was in site.adminProperties.
But maybe it's smarter to put it in extent.geometry ?

Here is what i have so far with only WGS84 :

	"extent" : {
		"geometry" : {
			"decimalLongitude" : '.$arrDetailsSites[$kartatx]["wgs84_lon"].',
			"decimalLatitude" : '.$arrDetailsSites[$kartatx]["wgs84_lat"].',
			"centre" : [
				'.$arrDetailsSites[$kartatx]["wgs84_lon"].',
				'.$arrDetailsSites[$kartatx]["wgs84_lat"].',
				6
			],
			"aream2" : 0,
			"type" : "Point",
			"coordinates" : [
				'.$arrDetailsSites[$kartatx]["wgs84_lon"].',
				'.$arrDetailsSites[$kartatx]["wgs84_lat"].',
				6
			],
			"areaKmSq" : 0
		},
		"source" : "Point"
	},

**Comment by magdziarek** [comment]
Why are you adding the centroid coordinates in another CRS? I think all other points should be displayed in another CRS possible but they never use centroids. Let's talk about this?

**Comment by mathieuLU** [comment]
ah ok, not sure they need that !
My idea was to store in the mongo database what they hae in PSQL. But maybe these fields are useless. 
At least they're not urgent ;-)

**Comment by magdziarek** [comment]
When flushing the database all sites can be deleted but if projects are kept then the sites that are project areas need to be kept as well. There will be one such site for each project. The name will be "Project area for {name_of_project}", eg.  "Project area for Vinterrutt"
