### ISSUE TITLE
Comments from surveys about sites need to be stored in site

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#116]
the volunteers need to display the comments of previous surveyors regarding site accessibility, etc. This information is saved in the survey form for standardrutt (and others?) but the surveyors don't have access to that (they can only see the data they recorded themselves)

**Comment by mathieuLU** [comment]
I don't think that a surveyor should be able to watch data registered by previous surveyors, even if it's only a field. 
From my point of view an admin task should be done in between, and these data (comments about the sites) should be copy-pasted at some point to the site.
Do you think we should make it automatic to copy-paste these info in the description field of the site ?

**Comment by magdziarek** [comment]
They shouldn't see the data related to the observations but they should see only that one field. Where this is important is when a volunteer books a site and they go to the site/index page for information. No one else can see this page. From there the volunteer should be able to download coordinates of the site, and save the map + any comments from previous surveyors as a pdf. Ideally, it would be automatic -> to avoid the person who enters the survey forgetting to record the information for the site. I will ask for feedback about this in this testing round
