### ISSUE TITLE
Survey forms: how do we mark when no species were recorded?

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#139]
On some routes, e.g. nattrutt and vinterrutt it is possible not to observe any species. I think there was a way of recording it in the excel spreadsheet, eg. a code like 999 or something?
@mathieuLU  When data is drawn from ecodata for analysis in R how do you recognize this situation in ecodata observations? Look at the output and see there is no data? Or how?

**Comment by mathieuLU** [comment]
no the art 999 is for another purpose (storing other metadata from observvation)
Actually the excel reports can be empty. Without any lines. In PSQL it means that there will be a art000 line, and then nothing else (maybe a art999 or art998 depending on the scehme, for other metadata)

Does that trigger an error if no species is added to the form ?

The best would be to let it possible to submit a form without any species entered. Maybe with a message saying "WARNING you're about to submit a form without any observation, do you confirm ?"

and then in the ecodata database we would have an output, with an empty data array, and no record. Which is fine
