### ISSUE TITLE
Import records from Excel spreadsheets: modify species field

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#142]
The species field had to be modified to contain the rank used by SFT instead if the scientificName field. Please include that, otherwise the sorting can't be done.  
Check:
#140

**Comment by mathieuLU** [comment]
So it would mean that for all the data already uploaded i should add the "rank" field ?
Or only for the new uploaded data from excel ?
well let's talk about it next time ;-)

**Comment by magdziarek** [comment]
Only the new uploaded data, please. Don't need to modify the existing records.

**Comment by mathieuLU** [comment]
I added it to the output json file. But should I do it as well for the record json ?

it looks like that in an output  :

"speciesMammals" : {
								"listId" : "dr159",
								"commonName" : "",
								"outputSpeciesId" : "6afb0d7b-158b-6f99-5ab3-983fdd453b02",
								"scientificName" : "Vulpes lagopus",
								"name" : "Fjällräv",
								"guid" : "5219303",
								"rank" : "4130",
							}


"species" : {
								"listId" : "dr627",
								"commonName" : "",
								"outputSpeciesId" : "61e192ce-e2f1-8623-1e73-85b2957e51d8",
								"scientificName" : "Charadrius hiaticula",
								"name" : "Större strandpipare",
								"guid" : "9566659",
								"rank" : "1270",
							},

**Comment by magdziarek** [comment]
Sorry, I still get confused with the species list. Why is there no common name? For the sorting scientificName has to have the value of the rank. Sorry for the confusion. 
So it should look like this:

```
"species" : {
"listId" : "dr627",
"commonName" : "",
"outputSpeciesId" : "61e192ce-e2f1-8623-1e73-85b2957e51d8",
"scientificName" : "1270",
"name" : "Större strandpipare",
"guid" : "9566659"
},
```
Btw, is there anything that would force us to have the scientific name as real scientific name?

**Comment by mathieuLU** [comment]
Wow ok I did not get that.

So :
 - commonName : swedish name right ?
 - name : swedish name ?
 - scientificName : the rank ?

it looks really strange to use another field to store the rank. And are you sure that it does not create any collateral damage ?
I mean, I guess this field is used elsewhere isn't it ? Maybe not, maybe the record collection prevails, for the export as DarwinCore for instance.

But does that mean that you will rename all the existing data to fit this new rule ? I guess all of them have to have the same format right ?

I guess you already thought about it but : 
 - is it impossible to sort by using another field from the species array ? Like with that rank field I have added. I guess not but I try to ask :)
 - couldn't we at least have a format like "RANK# scientificName" ? so that we keep the scientificName in the field

sorry for these questions, I guess I did not read your previous suggestion carefully since I discover it only now :(

**Comment by magdziarek** [comment]
I told you and Johan about this issue that I had with retrieving the rank from the lists module and using it there and using the speciesName as rank was the only way around it I found. Martin really wanted to sort by rank, he can't sort by anything else. I know it's an awful solution and I was never happy about it but it works for now and unfortunately I can't provide an alternative.

**Comment by mathieuLU** [comment]
yeah i remember well that you mentioned it to us. No worries. I simply did not get that it went that way. And i'm sure you evaluated the other options.

Well, does that mean that you will edit all the existing data to fit this new rule ? All the output, by putting the rank in the scientificName

**Comment by magdziarek** [comment]
I am happy to discuss it in detail some time. For now:
> * commonName : swedish name right ?
> * name : swedish name ?
> * scientificName : the rank ?

Yes

> it looks really strange to use another field to store the rank. And are you sure that it does not create any collateral damage ?
> I mean, I guess this field is used elsewhere isn't it ? Maybe not, maybe the record collection prevails, for the export as DarwinCore for instance.

It might create some damage if new projects come and want an entirely different thing but it doesn't now the way we use it.  

> But does that mean that you will rename all the existing data to fit this new rule ? I guess all of them have to have the same format right ?

No. Only newly added surveys need to be sorted.

> * is it impossible to sort by using another field from the species array ? Like with that rank field I have added. I guess not but I try to ask :)


not because i didn't find a way to retrieve arbitrary columns in ecodata-client-plugin from the lists module. I can only get the values that are called commonName and scientificName and you can display the combination of the two. To sort I also need to have the value inside the input field. Otherwise, we'd need to modify the lists module API or find another way to store the species + rank. 

> * couldn't we at least have a format like "RANK# scientificName" ? so that we keep the scientificName in the field

We could if you think it's better. So the original list would need to have a column that has this format "RANK# scientificName" and it would have to be matched to scientificName.

**Comment by mathieuLU** [comment]
> not because i didn't find a way to retrieve arbitrary columns in ecodata-client-plugin from the lists module. I can only get the values that are called commonName and scientificName and you can display the combination of the two. To sort I also need to have the value inside the input field. Otherwise, we'd need to modify the lists module API or find another way to store the species + rank.

So it means that it can be done by using the commonName (for storing the rank) instead of the scientificName ?

**Comment by magdziarek** [comment]
True but we want the commonName, we don't need the scientificName according the SFT. I am not sure what the "name" field is. I can only use commonName and scientificName in ecodata-client-plugin

**Comment by mathieuLU** [comment]
> No. Only newly added surveys need to be sorted.
So it means that historical outputs will have a "normal" format, with real scientificNames. But not the new ones ?

> We could if you think it's better. So the original list would need to have a column that has this format "RANK# scientificName" and it would have to be matched to scientificName.
I don't get why the list should be changed ?

And one extra question. I thought they were ranking the species by art, and not by rank in the excel files. But maybe it's kind of the same ranking ?

Well I have nothing better to suggest. But still i'd like to give it a deeper look to understand exactly how it works behind, because if it creates some collateral damage months after you leave, I'll have to know exactly the process.
Could we discuss it next week ?

**Comment by magdziarek** [comment]
> > No. Only newly added surveys need to be sorted.
> > So it means that historical outputs will have a "normal" format, with real scientificNames. But not the new ones ?
>
Yes
> > We could if you think it's better. So the original list would need to have a column that has this format "RANK# scientificName" and it would have to be matched to scientificName.
> > I don't get why the list should be changed ?
> 
because we can only get the values for two columns from the lists module unless we want to make changes that involve both ecodata-client-plugin and the lists module

> And one extra question. I thought they were ranking the species by art, and not by rank in the excel files. But maybe it's kind of the same ranking ?
> 

No, that's what I was hoping and initially did. I thought it was partly to avoid duplicates. It turned out that it was crucial for Martin and for the surveyors to order by the rank AND they needed an alert if they entered duplicate species. So now they have both :) But the solution, as I said, is awful, but the best I could do for now.
 
> Well I have nothing better to suggest. But still i'd like to give it a deeper look to understand exactly how it works behind, because if it creates some collateral damage months after you leave, I'll have to know exactly the process.
> Could we discuss it next week ?

Yes! Tell me when. I just need some advance to remind myself the details.

**Comment by magdziarek** [comment]
@mathieuLU  Now we can forget the above. You will need to modify your excel export but nothing else. The lists remain the same, the species field doesn't change. The only modification is adding a new column in the observations table and its value inside output.data.observations for each observation that has a species value in it.

 
The rework is that:
- the list has to have the rank column called "rank" (this is retrieved in SpeciesService in BioCollect - that's also where the column name "rank" is used)
- the form template json has to have a column right next to the species autocomplete with name: "swedishRank" -> see example standardrutt form template on the [Lund-University-Biodiversity-data repo](https://github.com/Lund-University-Biodiversity-data/biocollect_forms/blob/2ad17a3c1f6e548518a0136fa3633f00f8459a1a/standardrutter.json#L243)
- imported outputs for each observation have to have a value called "swedishRank" with a string outside of the species object (I didn't want to modify that since it adheres to standards now). So it should be like in this example:
```
{ output: 
data : {
observations: [
{
				"swedishRank" : "610",
				"individualCount" : 0,
				"L01" : "0",
				"L03" : "0",
				"L02" : "0",
				"P01" : "0",
				"L05" : "0",
				"L04" : "0",
				"P03" : "0",
				"L07" : "0",
				"pointCount" : 0,
				"P02" : "0",
				"L06" : "0",
				"P05" : "0",
				"species" : {
					"listId" : "dr158",
					"commonName" : "Kopparand",
					"outputSpeciesId" : "b20df8af-f317-44e5-835f-b1c98d8b9f9f",
					"scientificName" : "Oxyura leucocephala",
					"name" : "Kopparand (Oxyura leucocephala)",
					"guid" : "2498302"
				},
				"P04" : "0",
				"L08" : "0",
				"P07" : "0",
				"P06" : "0",
				"P08" : "0",
				"lineCount" : 0
			}
......
		]
```

**Comment by mathieuLU** [comment]
OK cool

I can easily add this swedishRank, based on the field rank of the list

Should that create a problem for the historical records ?
I guess they can't be sorted with this swedishRank field. WHat happens whenn we open one of them in BioCollect ?

**Comment by mathieuLU** [comment]
fixed by adding a swedishRank in the output
