### ISSUE TITLE
Survey forms: check for species entered twice

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#143]
“Under tiden som jag rapporterade stötte jag på ytterligare ett par tankar om det digitala systemet som ni kanske vill ha. Det ena rörde en undran om det verkligen blir rätt i fall man råkar skriva in en art flera gånger. Om jag hade skrivit bofink en gång redan och sen gjorde en ny art-rad med bofink så adderades en art till "totala arter" i protokollet. När jag sparade det som utkast och återkom till det senare låg det fortfarande kvar som en extra art, som att bofinken räknas som två arter bara för att den står på två rader. Om det inte åtgärdas bör man vara tydlig i instruktionerna kring detta, i fall det har betydelse för datainsamlandet vill säga. Det går ju relativt enkelt att med sortera-funktionen se om man råkat dubbelskriva en art men ännu smidigare skulle det vara om systemet varnade för att arten redan finns tillagd i en rad tidigare.”

ÅL: Short English version: Should there be a warning that a species has already been given a row, if one tries to add it twice?

**Comment by mathieuLU** [comment]
outdated
