### ISSUE TITLE
Vinterrutt data - different datasetNames

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#147]
Hej Aleksandra

For all my historical data, i used the dataset name "Vinterrutt". But it seems that BioCollect use "Vinterpunktrutt". See the details below

Which one should we use ?

> db.record.aggregate([
...     {"$match":{
...       "projectActivityId" : "ccace44f-c37a-44de-a586-7880128046d3"
...     }},
...     {"$group" : {
...     _id:"$datasetName", 
...       count:{$sum:1}
...     }},
...     {"$project": {
...         "datasetName" : 1,
...         "count" : 1
...     }},
... ]);
{ "_id" : "Vinterpunktrutt", "count" : 223 }
{ "_id" : "Vinterrutt", "count" : 850960 }
>

**Comment by magdziarek** [comment]
@mathieuLU  I asked Åke and he prefers Vinterpunktrutt when it's displayed to users. I think the value from record isn't displayed anywhere, it's the for DWcA but I understand you want to keep it consistent. Should we just change it for the 850 000 records in mongo? :)

**Comment by mathieuLU** [comment]
db.record.updateMany({
	datasetName:"Vinterpunktrutt"
},
{
	$set:{
		datasetName:"Vinterrutt"
	}
})

db.record.updateMany({
	datasetName:"Sommarpunktrutt"
},
{
	$set:{
		datasetName:"Sommarrutt"
	}
})
