### ISSUE TITLE
Site edit: for bookable sites add a comment field

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#149]
only for admin, only for booking. for a view in intranet that helps to manage booking

remember to remove the field after the field season

**Comment by magdziarek** [comment]
@mathieuLU  the field is called bookingComment and is a string

**Comment by magdziarek** [comment]
commit f64eb99d6777c95d2bbf338a15f3014f83804527

**Comment by mathieuLU** [comment]
I can't see it on these 2 examples:
(NATT) https://biocollect.biodiversitydata.se/sft/site/edit/86f5e3c0-a356-0ef1-a846-84649c8424bd
(STD) https://biocollect.biodiversitydata.se/sft/site/edit/2651c765-385d-4aa7-a3ec-086da60ad85e

Where is that field supposed to be edited in BioCollect ?

**Comment by magdziarek** [comment]
I assume you change the url manually? It should be editSystematic not edit in the URL
Our form is completely different so I had to build a different view. For your examples you can see this field here:
https://biocollect.biodiversitydata.se/sft/site/editSystematic/86f5e3c0-a356-0ef1-a846-84649c8424bd
https://biocollect.biodiversitydata.se/sft/site/editSystematic/2651c765-385d-4aa7-a3ec-086da60ad85e

![image](https://user-images.githubusercontent.com/26426498/132498162-e791ddc7-6dfd-4eb9-be95-43270d6cf70f.png)

**Comment by mathieuLU** [comment]
Great !!
Thanks a lot

**Comment by magdziarek** [comment]
Aaaa - sorry, do you think it should also maybe be inside the adminProperties array? 
It wouldn't be displayed to the volunteers anyway, but maybe for consistency I should move it to adminProperties?

**Comment by mathieuLU** [comment]
hmmm true.
well spotted
yes all the admin fields should stay in the admin part!

**Comment by magdziarek** [comment]
Will work on it this week #156

**Comment by magdziarek** [comment]
Changed it now to be adminProperties.bookingComment. Sorry for the delay.
Please adjust your script, @mathieuLU  and close this issue when ready.

**Comment by mathieuLU** [comment]
Great job !

**Comment by mathieuLU** [comment]
I changed my script as well
