### ISSUE TITLE
CAS login page - always need to log in twice

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#16]

**Comment by magdziarek** [comment]
it doesn't seem to be a problem on the production page @mathieuLU ?

**Comment by mathieuLU** [comment]
When did it happen last ?
I don't recall that bug on my side or production site

**Comment by magdziarek** [comment]
I have always had this problem when running locally. Not sure if it was ever a problem on production. I will close this then.

**Comment by magdziarek** [comment]
@mathieuLU  Reopening this as I see I still get this problem and SFT people were getting it too. Let's monitor if this is consistent, something to discuss in the meeting with Manash as well.

**Comment by magdziarek** [comment]
I will start posting when this issue occurs. Logging in from:
https://auth.bioatlas.se/cas/login?service=https%3A%2F%2Fbiocollect.bioatlas.se%2Flusm%2Fproject%2Findex%2F50b1cb29-cf33-4d43-a805-b07ae4de1750

**Comment by magdziarek** [comment]
It doesn't seem to happen when logging in on ecodata

**Comment by magdziarek** [comment]
Seems like Manash's solution worked - the main config file in /data/biocollect/config/biocollect-config-grails3.properties was missing values for CAS, the following lines should all be there:
```
# CAS Config
#
security.cas.appServerName=http://localhost:8087

security.cas.casServerName=https://auth.bioatlas.se
security.cas.casServerUrlPrefix=https://auth.bioatlas.se/cas
security.cas.loginUrl=https://auth.bioatlas.se/cas/login
security.cas.logoutUrl=https://auth.bioatlas.se/cas/logout

```

**Comment by magdziarek** [comment]
That solution maybe didn't work? A few people reported this is still an issue. 
Config files still the same but maybe now a value from the application.yml file is interfering? The behaviour is still inconsistent. I tried now several times and each time it worked the first time but I know the issue still occurs sometimes. @mathieuLU

**Comment by shahmanash** [comment]
Please check the config file against this template 
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocollect/templates/biocollect-config.properties

The value

`security.cas.appServerName=http://localhost:8087 `

should probably be the following in production

`security.cas.appServerName=https://biocollect.bioatlas.se`

**Comment by magdziarek** [comment]
Sorry, I  should have clarified, that was an example config from the test server. On production we have security.cas.appServerName=https://biocollect.bioatlas.se

**Comment by mathieuLU** [comment]
I guess we can close that one now ;-)
