### ISSUE TITLE
Punktrutter sites: when created a prefix should be added to the name

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#160]
Currently, when a new site is created, the name is entered in an input field by the user. So it can be whatever arbitrary name and names can be duplicated - there is no check for whether the name is unique.
Sites for punktrutter should follow this format:
personnummer-ruttnummer-nameEnteredByUser, eg. "530212-1-03-Paviken/Kronholmen"

This requires a change to projectActivity settings if we want to avoid a situation where the ID of the scheme changes and this stops working or if we want other schemes to be able to use a prefix for a site. If we want this available for others, we have to configure what the prefix should be. Would it be the name of the field that should be a prefix? How do we know which collection it should come from? There are so many issues with this and it's only used for one scheme so maybe it's fine to hard code it? 

When saving a site, check what scheme it's saved for. If it's sommar- or -vinterrutt then retrieve the user's internalPersonId.

TO DO:
- [x] #162
- [ ] #163
- [x] projectActivity has to have a place to configure that a prefix is needed and what the prefix should be
- [x] on site/update and site/create take the internalPersonId and concatenate it to the site.name before saving it

**Comment by mathieuLU** [comment]
Does it have to be automatic ?
Of course for sommar/vinter routes it's easy to add the personnummer. But for the route number ?

I think that in any case it will have to be reviewed and maybe edited by admins. So I think you should not take too many time trying to create the perfect automation process. Removing the special characters, adding the personnummer.

The key thing is to make sure that it fits the template for site names.

**Comment by magdziarek** [comment]
You  mean we could leave it up to the user who is creating the site to provide the correct name and when the admin checks the site, they add the personnummer? A good point I hadn't considered!

**Comment by mathieuLU** [comment]
The user can have instructions, but whatever he/she will add it will never be perfect. And I'm quite sure that an automation script won't be able to consider all the options for all the schemes. So far they have always created the site names themselves, so I'm not sure it should stop ?

I don't know actually, it's an open question

**Comment by magdziarek** [comment]
Closing this as we agreed it will be done manually by the admins
