### ISSUE TITLE
make site.name a unique field

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#162]

**Comment by magdziarek** [comment]
@mathieuLU  - are the site names even for the centroids that are placeholders unique? It seems like it to me but I wanted to make sure before I make the field unique
> db.site.find().count()
4270
> db.site.distinct("name").length
4270

**Comment by mathieuLU** [comment]
yes they are. Because I have already created the displayed name as "code + original route name"
but there are doublons in the original route names. Which is not a problem

=> not need to be unique
