### ISSUE TITLE
Record-date instead of output-date in the "all observations" page

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#175]
In IWC, there are many surveyx without a singl observation. => no record
the "all observations" page and the filter are using the record-eventDate

It should be better to have the surveyDate from output there

**Comment by mathieuLU** [comment]
New example

https://biocollect.biodiversitydata.se/sft/bioActivity/index/2d097f74-32da-45bb-94fc-b680c4f89505?returnTo=%2Fsft%2Fproject%2Findex%2F50b1cb29-cf33-4d43-a805-b07ae4de1750

<img width="604" alt="image003" src="https://user-images.githubusercontent.com/50901365/160554299-368b09e1-1bf3-4cbe-bbec-30ed4b7df0be.png">

**Comment by mathieuLU** [comment]
Same problem of the one recently opened by Åke => https://github.com/biodiversitydata-se/biocollect/issues/237

The data in this view (All Records) come from the collections activity/records. The surveyDate is stored in the records. But for our activities (= surveys) without any records ( = 0 observation) then we don't have any surveyDate to retrieve.
The surveyDate is stored in the Output object, which is not used in this view.

I spent a couple of hours trying to find an easy way to fix this. Unfortunately I'm afraid it means a big change of the data mapping for this view, in order to get the output data. I contacted the ALA people for help, to see if they have an easier way to fix this.

**Comment by fredrikhaas** [comment]
The ”problem” with Invalid date is far from uncommon in IWC-January.

**Comment by mathieuLU** [comment]
it works now !
![Screenshot from 2023-03-11 14-39-49](https://user-images.githubusercontent.com/50901365/224487954-35a17782-f8dd-4d4f-bb5b-90b6383cfcfe.png)

**Comment by mathieuLU** [comment]
fixed now with => https://github.com/biodiversitydata-se/ecodata/commit/305de7672a03386107a41094fd1583a78596abfd

The problem was with the way the data is reindexed. Now the output is obtained and the date is taken from there.
