### ISSUE TITLE
Bug in Excel import function : error says duplicate

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#178]
(Åke's message, 28 december)

Whereas there seems to be no problem (unfortunately) to import duplicate surveys (see below on 27 December ÅL/MG: Protocols occur in duplicates), MG had the opposite problem today. He tried to import two sommarpunktrutt-surveys from 2020. He tried to import Excel-protocols “Som20-610117-1-#09” and “Som20-610117-1-#10” (Mellösa and Nacka-Erstavik), but “computer says no”:  
"NO => period already exists in MongoDb"
Not sure what it means, but there are no surveys for these routes from 2020 in the system. MG also double checked the files and they are OK as they are with dates and everything.

**Comment by mathieuLU** [comment]
2 things : first the check was missing the status of the activity. In the very first example (Som20-610117-1-#9) the existing activity (4b150a42-ebe0-5ddb-8dc8-753f945461b8) was already deleted
Now the tool is checking the status as well to avoid the deleted activities.

 BUT the tool suddenly said that for this very specific route, there was already an activity created. 
https://biocollect.biodiversitydata.se/sft/bioActivity/index/effe0bdc-6616-0573-693f-d517d82287e3

But this one is 2021, not 2020, for the same reason as the previous bug (YEAR-1 for SOMMAR...)

I fixed it now ! I let you check and close.
I let the 2 files on the FTP server, ready to be imported...

**Comment by ekol-ali** [comment]
It worked. The two protocols were succesfully imported via the function in Intranet.
