### ISSUE TITLE
When extracting sommar-records, the year should stick to the date

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#180]
When exporting vinterpunktrutter to Excel in Intranet, there is a function to give the correct “year” (=winter season), so that a survey carried out 2020-12-28 gets Year=2020, and a survey 2021-01-01 also gets Year=2020. So, after New Year, it is “minus one year”. This works fine! However, it seems to be (erroneously) applied also to sommarpunktrutterna. It shouldn’t! 
FYI: It is not in operation on Nattrutter and Standardrutter.

**Comment by mathieuLU** [comment]
Fixed !!

Du kan kontrollera och sedan "Close with comment" the issue ;-)

**Comment by ekol-ali** [comment]
I just did an extraction and it works fine!
