### ISSUE TITLE
Permanently delete surveys

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#187]
After deleting a survey, maybe because it was a duplicate or just erroneous, it will no longer appear in the Excel-extract and no longer when searching among Data, e.g. https://biocollect.biodiversitydata.se/sft/project/index/b7eee643-d5fe-465e-af38-36b217440bd2 

Fine!

However, they still appear on the Personal sides, e.g. https://biocollect.biodiversitydata.se/sft/person/edit/c8020457-c221-d8db-0f9e-2f6b0c0b8a3c/?returnTo=/sft/project/index/b7eee643-d5fe-465e-af38-36b217440bd2#activityList

There you can see duplicates, although one of them apaprently is just a "ghost". When clicking you get "page not found". 

I presume there should be a general solution to this, but here are some examples of surveyes that should be deleted: 
- 980314-1-01 - TAMBERG, surveyed 2021-12-23. 
- 600827-1-01 - SNYTEN-BLOMDAL, surveyed 2021-0529. It occurs in **duplicate**. One has data in it, so it’s fine. The other one is empty of data. Please delete the latter. 
- 430426-1-03 - KNISA, surveyed 2021-05-21. It occurs in **duplicate**. One has data in it, so it’s fine. The other one is empty of data. Please delete the latter.

**Comment by mathieuLU** [comment]
fixed with the daily automated script that export/compress/remove the deleted objects from the database
