### ISSUE TITLE
Aleksandras mail address on automated generated e-mail

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#188]
When we at SFT get an automated mail that a new person wants to join BioCollect, Aleksandra's mailadress is given as sender.

**Comment by mathieuLU** [comment]
please forward me one of these emails ;-)
I found one place where her email was set in biocollect. I fixed it. But it was not as a sender. So i guess her name remains somewhere

**Comment by mathieuLU** [comment]
Do you mean this kind of email ?

![Screenshot from 2022-01-11 14-54-21](https://user-images.githubusercontent.com/50901365/148955489-011b2e9c-b454-4486-b597-dfc39cd2b6cb.png)

**Comment by mathieuLU** [comment]
ah ok i received your message. It was not as a sender, but as a CC.

![Screenshot from 2022-01-11 15-09-03](https://user-images.githubusercontent.com/50901365/148958049-12f94174-aad5-439a-a154-3460dbd33019.png)

And that's the one I fixed, as you can see in my previous message!


I let you close that one ;-)

**Comment by ekol-ali** [comment]
Case solved!
