### ISSUE TITLE
Survey in BioCollect does not show up in Excel-export

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#189]
This survey

https://biocollect.biodiversitydata.se/sft/bioActivity/index/6054e86c-a8e2-4e10-a3a6-8ec05461de69

does not appear when exporting through the tool in Intranet. It was reported through BioCollect (if important info).

**Comment by ekol-ali** [comment]
The same holds for this survey:

https://biocollect.biodiversitydata.se/sft/bioActivity/index/70f499c6-b64f-4002-a220-f99910831284

Also this sruvey was reported through BioCollect (if important info).

**Comment by mathieuLU** [comment]
Hej Åke

These 2 have the status : under review 
=> Only the validated surveys are exported. From my point of view this behaviour is ok, it's not a bug

Do you think the export tool should export as well the "under review" surveys ?

**Comment by ekol-ali** [comment]
OK, so the problem is all on the handling side! Sorry! I have written to martin about it in a separate mail. 
I think we should keep the export as it is for the moment.

**Comment by mathieuLU** [comment]
argh ok
I changed the export actually, to add the "under review" as well. ANd a a "status" column so you can use it to filter.
