### ISSUE TITLE
Not possible to create and save new point route

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#190]
At least two persons have reported that they when creating a new point count route, they just got the answer "Could not save site". I presume this problem is connected to issue #177, where routes with all 20 points defined cannot be edited and saved, whereas routes with only one coordinate can.

**Comment by ekol-ali** [comment]
What do you think, can this be closed as well?

**Comment by mathieuLU** [comment]
should be solved ;-)
