### ISSUE TITLE
When a person is created, the projects field is missing

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#194]
10 persons where in the database without the field projects

to check how it works when a person is added.

manual fix was :
db.person.updateMany({
	personId:{
		$in : [
		"bbb49420-3512-4b8a-b335-986fed3e4291", 
"9c3c5d54-9375-4e24-aa40-405c398d8d99", 
"ad0daaab-04c5-4592-9512-288880dac5da", 
"0b87f888-c35c-42ee-8ec9-7010b98dc897", 
"e70d6ffe-7a12-4968-a9ee-7f0c1c8ede26", 
"4ede4c4f-6316-4b79-856f-7a6141074e01", 
"073f1447-1288-4a24-ab72-30be1cbd475d", 
"701fd502-3c8b-4405-9089-fa1a786591bd", 
"e417d3e1-3d95-4a30-88bc-ec0e045e91d6", 
"dfc820c5-4ce6-418f-b721-95ca176bda7f" 
		]
	}
}, 
{
	$set: {
		"projects" : [
			"89383d0f-9735-4fe7-8eb4-8b2e9e9b7b5c",
			"d0b2f329-c394-464b-b5ab-e1e205585a7c",
			"b7eee643-d5fe-465e-af38-36b217440bd2",
			"49f55dc1-a63a-4ebf-962b-4d486db0ab16",
			"50b1cb29-cf33-4d43-a805-b07ae4de1750"
		]
	}
}
)

**Comment by mathieuLU** [comment]
same here, with all the persons created recently :
db.person.find({projects:{$exists:false}},{personId:1, firstName:1,lastName:1,dateCreated:1}).pretty()

same manual temporary fix

**Comment by ekol-ali** [comment]
Thanks, that removed two of the five "missing persons". It will most likely be the same problem with Nattrutter, I presume?

**Comment by mathieuLU** [comment]
yes

**Comment by mathieuLU** [comment]
Fixed with commit on ecodata https://github.com/biodiversitydata-se/ecodata/commit/b2d2a2e43d9d41199d45c5afb68ede6527d9d0a6

database clean 

> db.person.find({projects:{$exists:false}}).count()
0
