### ISSUE TITLE
Possibility to extract lists of surveyors  (on Intranet)

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#195]
We regularly send out group mails to MANY people, normally to all, or a subset of, "now active" surveyors. To do this now is a rather tedious job. We would like a function in Intranet where we can ask for a list of (a subset of) surveyors. 

The extract (Excel) should contain: personId (like 610814-1), fornamn, efternamn, adress, postnr, city and (most importantly) e-mail address.

We would like to be able to filter on: 
YEARS 
PROGRAMME i.e. sommarpunktrutter, vinterpunktrutter, IWC, standardrutter .

**Comment by mathieuLU** [comment]
replaced by https://github.com/Lund-University-Biodiversity-data/intranet-ekol/issues/1
