### ISSUE TITLE
Remove some options for subspecies when reporting in BioCollect

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#210]
The subspecies listed below are now possible to use by the surveyors when entering data in BioCollect. These codes are only used by us in analyses of the data and should not be an option for the surveyors.

![image](https://user-images.githubusercontent.com/96691702/151508176-5c058a1f-5c69-4e57-be7c-649d09da0db4.png)

Can these be removed from the list when entering data? We do want them at he admin side when analysing data?

**Comment by mathieuLU** [comment]
which delprogramm is this ?
could you please provide me an example ?

I can't find a single record in the database that contains "Nordlig"/"Sydlig" for instance

**Comment by ekol-ali** [comment]
Apparently there is no problem left to be solved!
