### ISSUE TITLE
No swedishRank in the form for sjöfåglar. why ?

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#217]
https://biocollect.biodiversitydata.se/sft/bioActivity/index/50b24fed-6f6a-4f83-a4de-c198c3843494?returnTo=%2Fsft%2FbioActivity%2FallRecords

not displayed and NOT STORED !

**Comment by mathieuLU** [comment]
linked to https://github.com/biodiversitydata-se/biocollect/issues/230

now the column shows up. But I have to check if it's ok in the database

**Comment by mathieuLU** [comment]
database fixed, with swedishRank for all the IWC historical records

only 6 activities to check manually : 

logs:
[2022-12-14 16:48:32] ERROR : No species info for activityId#3ba47d6f-8432-4fbd-b76f-054aeee27e51 and Anser fabalis rossicus Buturlin, 1933/guid#:6178319 => maybe the guid changed ?
[2022-12-14 16:48:32] ERROR : No guid for activityId#2d00d8ae-6e9c-48a4-9e4f-495dc8290c84 and  (list: )
[2022-12-14 16:48:32] ERROR : No guid for activityId#1982351f-8e41-49ed-842e-4b4be0cf5691 and  (list: )
[2022-12-14 16:48:32] ERROR : No guid for activityId#1a8eac2b-60b0-49fc-8d7d-bf00d29e52b2 and  (list: )
[2022-12-14 16:48:32] ERROR : No guid for activityId#6eb63b11-a56e-494e-9249-be5e928b0e80 and  (list: )
[2022-12-14 16:48:32] ERROR : No guid for activityId#6eb63b11-a56e-494e-9249-be5e928b0e80 and  (list: )

the last five are only empty rows to delete I guess.

the first one is a real species to fix i guess => https://github.com/biodiversitydata-se/biocollect/issues/217

![Screenshot from 2022-12-14 17-51-25](https://user-images.githubusercontent.com/50901365/207657575-3f29dd52-d217-4eb6-bb2e-a9f67314c05f.png)

please confirm @fredrikhaas that it's ok for you ;-)

**Comment by fredrikhaas** [comment]
Hej Mathieu!
Om jag gjort rätt så är det bara ett activityID som gäller sjöfåglar, de andra leder till Vinterpunktrutter eller Nattrutter. Jag har åtgärdat Tundrasädgåsen hoppas jag. Jag gick till protokollet och lade in Tundrasädgåsen en gång till och då fick den en rank. Sparade sen.

/Fredrik

”https://biocollect.biodiversitydata.se/sft/bioActivity/edit/3ba47d6f-8432-4fbd-b76f-054aeee27e51
Sjöfågel jan/sep. Tundrasädgåsen åtgärdad. Begriper inte varför den inte fick någon rank, men nu har den det.

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/2d00d8ae-6e9c-48a4-9e4f-495dc8290c84
Vinterpunktrutt - not approved

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/1982351f-8e41-49ed-842e-4b4be0cf5691
Vinterpunktrutt - not approved

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/1a8eac2b-60b0-49fc-8d7d-bf00d29e52b2
Vinterpunktrutt - not approved

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/6eb63b11-a56e-494e-9249-be5e928b0e80
Nattrutt - not approved (är listad 2 gånger av dig)”

**Comment by mathieuLU** [comment]
Perfekt, tack Fredrik !
