### ISSUE TITLE
Updating and extracting surveyor information for standardrutter in BioCollect

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#224]
- When surveying "**standardrutter**", the surveyors can write free text. When reporting directly in **BioCollect**, it goes into two fields:  one about the bird observations called "Kommentarer - specifikt om observationer av fåglar" and another one about practical aspects called "Kommentarer - Noteringar om avvikelser, överhoppningar, pauser, svåra passager, annat rent praktiskt mm"
- Up to 2020 these comments were mixed, and are presently in BioCollect in the box called "Kommentarer - Noteringar om avvikelser, överhoppningar, pauser, svåra passager, annat rent praktiskt mm".

- This winter, Sissel Sjöberg went through all of the comments from **1996-2020** and separated them into "practical" and "bird" comments. The sepatated texts exist in an Excel-file. 
[Inventerarkommentarer Standardrutter-1996-2020 (Sissel).xlsx](https://github.com/biodiversitydata-se/biocollect/files/8679843/Inventerarkommentarer.Standardrutter-1996-2020.Sissel.xlsx)
We would now like the following to happen:

1. Remove all the free text information for standardrutter for 1996-2020 from the two boxes. **Leave data for 2021** (and 2022, if somebody happens to report soon)
2. Import all the separated text from the Excel-file into the correct "boxes" 
3. Create an extract function in the Intranet, where we can get a file out for standardrutter with columns: Karta, Yr, Birdinfo, Praktisk info.

**Comment by mathieuLU** [comment]
The point 3 is ok 
"Create an extract function in the Intranet, where we can get a file out for standardrutter with columns: Karta, Yr, Birdinfo, Praktisk info."
=> 
https://canmove-app.ekol.lu.se/intranet/tools/extract_excel_custom.php

**Comment by ekol-ali** [comment]
Looks good. Are you done with the full conversion as well (points 1 and 2), or is this just trying out point 3?

**Comment by mathieuLU** [comment]
ok points 1 and 2 seem ok

so based on the fixed excel file (with the correct site karta), i scan all the lines, and remove the existing data for surveys 1996-2020, and replace them by the new ones from the file.

the script will take a while to scan the 8210 lines of the file

one specfic thing : if a line is missing in the excel file, the comments won't be changed in the ecodata-database.

**Comment by mathieuLU** [comment]
seems ok to me. details sent (email)
