### ISSUE TITLE
Surveys received with empty mandatory fields

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#226]
https://biocollect.biodiversitydata.se/sft/bioActivity/edit/4591e4a9-cc06-4722-8e19-edf5fdce3760
https://biocollect.biodiversitydata.se/sft/bioActivity/edit/07a5efed-930d-416d-bdcc-1e3e5fa5d10c;jsessionid=AF2D9381FB2E1A3C7AB9C28B118071E8
(maybe already fixed by Fredrik)

even the date is empty. All these fields are mandatory and I can't reproduce the problem. 
Several users have done that already.

![Screenshot from 2022-09-28 09-30-00](https://user-images.githubusercontent.com/50901365/192716482-15dec837-5d84-4657-b131-87b86025548e.png)

**Comment by mathieuLU** [comment]
Fredrik was able to reproduce the problem : 
first fill in the form by filling in all the forms, validate
then, in order to fill in a second survey, click on the "go back one page" of your web browser to obtain an empty form again. Here are the fields already filled in like for the 1st form. BUT when you save, these fields aren't saved.

=> this bug has to be fixed 

AND
there should be an easier way for the surveyors to save multiple surveys in a row. Without being tempted to use the "go back one page" button of the web browser.
Options : 
 - open a new empty form after one is created/sent ?
 - when you click on "Rapportera resultat" => "Sjöfåglar, januari/september", it could open a nnew tab. Then you filll in your form and you can close it once it's done. SO you're back to the very same page and just have to click again on "Sjöfåglar, januari/september"

**Comment by mathieuLU** [comment]
ok after investigation, here is what I found.

after validating a form (skicka), the user ends up on the index page a of a survey : the page that displays the content of the survey, what the user just entered. Which is ok.

If the user clicks on the "back page" button of his/her browser, the user will get again the form pre-filled, ready to be validated. ANd then he/she can revalidate, but unfortunately the data won't be saved, as Fredrik noticed it (see post above).

first : it happens with Chrome, but not Firefox. For some reason, pressing on the back button does not reload the form in Firefox. 

Then : how can we avoid that. If I understood it well, some users may have tens of surveys to add in a row. Being forced to click again on Hem => rapportera => etc... is quite boring. That's why they shortcut it.

After analysis, here is the best solution from my point of view : 
on the pages to view a survey, adding 2 buttons "Edit" (if the user is allowed to edit), and "add a new record". Like that :
![Screenshot from 2022-11-29 15-28-59](https://user-images.githubusercontent.com/50901365/204558003-e81898ee-fb0b-467a-acf6-bb76c996f64d.png)

Which means that if a user has multiple forms to add, she/he will proceed this way : 
 - rapportera resultaten, filling in the form for the survey
 - validating
 - she/he lands on the view page of his/her survey (which is always a good thing to have a chance to check what you just entered). And then he only has to click on "add a new record".

This layout (with the 2 buttons "edit" and "add a new record") is the default layout in BioCollect. For some reasons, Aleksandra has removed these buttons, maybe it was agreed between all of you. FOr instance maybe the BioCollect users are not supposed to be able to edit their own submitted records. So it may be good to keep the "edit" button hidden. No problem

Let me now if we should display the "add a new record" button, it may solve this problem.
Of course this button can be added on top of the page.

**Comment by ekol-ali** [comment]
Hej Mathieu, I will leave to Fredrik to have the final word here. I can only respond to the Edit-button-question. Yes, indeed we do have as a basic rule that he surveyors should NOT be able to edit what they once submitted. It has to go through us. To avoind all sorts of potential problems and confusion.

**Comment by mathieuLU** [comment]
Button added. I put on top on thee page. Instead of having it at the end. TO make sure that the button is visible after entering some data ;-)
![Screenshot from 2022-11-30 13-19-55](https://user-images.githubusercontent.com/50901365/204795048-e54b744d-7aad-4c63-9f2e-9ae53b2d04ad.png)


@fredrikhaas i let you close the issue if you think that the problem is solved!
