### ISSUE TITLE
Codes for sex of person in Intranet extract

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#231]
There are three alternatives when assigning a person to "sex": Man, Kvinna, or Annat. That's fine. When in intranet I am extracting data on the surveyors (=Personer), sex comes out as M for Man and F for Kvinna. That's also fine. However, Annat comes out as Annat, which is inconvenient when importing into SQL.

In the Intranet extract, please change "Annat" to "X"

**Comment by mathieuLU** [comment]
done with https://github.com/Lund-University-Biodiversity-data/convert-SFT-SEBMS-to-MongoDB/commit/623ffcbdc8055f714a9fd9892f7fc9f1c8673fd2
