### ISSUE TITLE
It should not be possible to register unspecified species names

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#232]
ÅL: På rutten 05G2H fanns två arter utan artnummer, men där artnamnen fanns med. Detta skall väl inte gå?
MB: Man kan lägga till data i BioCollect utan en känd art. Jag har precis provat med nattrutterna.

It would be good to only allow species name that have been chosen from our own species list.

**Comment by mathieuLU** [comment]
I think I found a technical solution to deal with it. Thee message "Ej listad eller okänd art" would still appear, but it won't be clickable anymore.
So the user has the information but cannot validate the species name.

Would that work for you ?

And do you confirm that ALL the delprogram need that feature ?
it's easier to do for all, so I want to make sure that it's not something specific for STD eller NATT

**Comment by ekol-ali** [comment]
I am not sure I fully understand exactly what happens, but since the surveyor is already used to having to choose a preset species, it should work. 

As far as I can see, this is a potential problem for ALL schemes.

**Comment by mathieuLU** [comment]
all good

now the surveyors cannot select a species that is not part of the species list. They can't click anymore on the "ej listad eller okänd art" item

@fredrikhaas
