### ISSUE TITLE
When a new route is created and "sent in", give the person a note that "you have to wait"

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#233]
When a new point count route is created, we as admin repeatedly get several notes by mail that a route is created. Not just one note. This is because the person who created the route doesn't understand that the route is in the system and the (s)he needs to wait for an OK from us. They therefore submit the route several times. It is in the instructions, but "not all read instructions"....

We would like to have a function that, when the person has "sent in" the new route, says something like: 

"Stort tack! Din nya punktrutt är registrerad. Den skall nu godkännas av projektledningen. Du kommer att få ett mail när den är godkänd. Först då kan du rapportera data för rutten".   

We only need this function for point count routes.
Åke

**Comment by mathieuLU** [comment]
Hej Åke
The way you describe it, the only place to put this message would be the "site index" page (the page displayed once the site is created). 
But since this required modification is only for a specific delprogram, i'd rather put it on the dedicated form. Editing the site-index page, which is a core page and subject to later modifications from ALA, could be a problem.

So my suggestion would be to add the text right above the submit button of the form, here :
![Screenshot from 2023-02-07 10-01-13](https://user-images.githubusercontent.com/50901365/217199286-50424ca1-079d-4b00-b2b4-55377b5b18e6.png)

Since the form already uses several helptexts ("steg 1:...), i think it would make sense to have it here.

Let me know. Andd if you're ok with this suggestion, please send me again the modified text you would like to display :)

**Comment by ekol-ali** [comment]
I think the placement sounds OK. If I get you right, there can be no pop-up as a result of pushing "Spara ändringar", but rather a text to read BEFORE they push "Spara ändringar"? If so, that text could rather sound like this:

"När du är klar med din rutt, klicka på Spara ändringar. Då registreras din nya punktrutt hos oss. När vi godkänt rutten skickar vi dig ett mail. Därefter kan du börja registrera data för rutten."

I'd be happy of Fredrik could comment upon this too, before going sharp.

**Comment by mathieuLU** [comment]
suggestions : 
![Screenshot from 2023-02-08 11-26-55](https://user-images.githubusercontent.com/50901365/217504170-a512dad6-8f76-433c-addb-8e3df3e3505e.png)

![Screenshot from 2023-02-08 11-27-19](https://user-images.githubusercontent.com/50901365/217504165-8d9f802f-b696-4cc6-876d-8599e7dd060f.png)

@fredrikhaas vad tänker ni om det ?

**Comment by fredrikhaas** [comment]
Hej!
Tycker att det ser utmärkt ut.

/Fredrik

**Comment by mathieuLU** [comment]
bara en fråga. Varför är det bara för punktrutterna ?
Behöver ni den också för nattrutterna ? Användare kan skapa nattrutter också.

**Comment by ekol-ali** [comment]
Bara en fråga, men en bra fråga!
Vi kan absolut ha samma text även för nattrutterna. Däremot är det en stor skillnad då väldigt få nya nattrutter skapas varje år och då alltid efter en aktiv kontakt mellan inventeraren och Martin. Men jag tror inte det skadar att ha samma text där!
Alltså - kan du lägga dit samma text för nattrutterna blir det bra och så får Martin tycka till om den skall vara kvar.

**Comment by mathieuLU** [comment]
i texten finns det "Då registreras din nya punktrutt hos oss."
kanske kan vi byta till "Då registreras din nya rutt hos oss."
så funkar det för både 2

**Comment by ekol-ali** [comment]
Jättebra förslag
Fast ännu bättre blir "Då registreras den nya rutten hos oss" på båda, eller åtminstone på nattrutten. Nattrutterna är ju inte personliga, som punktrutterna. Rent formellt finns inte "min nattrutt", även om vi all ofta säger så.

**Comment by mathieuLU** [comment]
Published ! 
https://github.com/biodiversitydata-se/biocollect/commit/57c307a50aaba3ebbbd504280ee5d55f85834de0

**Comment by ekol-ali** [comment]
Kanon!
Åke

Från: mathieuLU ***@***.***>
Skickat: Wednesday, 8 February 2023 16:57
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] When a new route is created and "sent in", give the person a note that "you have to wait" (Issue #233)


Published !
57c307a<https://github.com/biodiversitydata-se/biocollect/commit/57c307a50aaba3ebbbd504280ee5d55f85834de0>
