### ISSUE TITLE
Allow users to unbook routes (IWC) and send an email to the admins when they do

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#234]
from @fredrikhaas 
`Det hade varit bra om inventerarna själva kunde avboka sina kustrutor och sjöfågelområden (iwc). När inventeraren avbokar hade det varit bra om det skickades ett meddelande till oss om att så skett.`

Design to be determined

Change title of "uppdatera min profil" (add infos about site bookings handling and previous surveys)
Show the 3rd tab for all users with Lokalbokning. Only "visa bokade lokaler"

+ avboka button 

+ confirmation email to admins

**Comment by mathieuLU** [comment]
Hej Fredrik.

Here is what we could do : 

Right now on the homepage every user can see the link "Uppdatera min profil". This page allows a user to edit his profile information and his surveys. We could add there a tab "Lokaler"

so first, from my point of view the item menu should be renamed. ""Uppdatera min profil, se mina undersökningar och bokningar". Well something like that :) Your choice.

When you click that link, you can now see 3 tabs (admin could already see the "Lokalbokning" tag. Now every user could see it : 
![Screenshot from 2023-05-11 13-22-42](https://github.com/biodiversitydata-se/biocollect/assets/50901365/20b32ce8-0fc5-4bc2-97fd-c553ce35600d)

An admin can see 3 blocks there. A regular user would see only the middle one (or maybe the last one as well ?)
![Screenshot from 2023-05-11 13-27-34](https://github.com/biodiversitydata-se/biocollect/assets/50901365/d16a08fb-9992-4d08-b5f8-483e57b8042a)

Right now, clicking on "avboka" displays this : 
![Screenshot from 2023-05-11 13-28-09](https://github.com/biodiversitydata-se/biocollect/assets/50901365/86ccc988-043a-464c-a499-58fcfc2a6d1c)
![Screenshot from 2023-05-11 13-30-55](https://github.com/biodiversitydata-se/biocollect/assets/50901365/53731db6-3f33-4bf8-a8cc-dd35704067e9)

so we have to translate this. Let me know what should stand there ;-)

ANd in addition, of course, an email has to be sent to the admin, saying that the site has been unbooked. PLease tell me as well what we should write there :)

Let me know if it looks fine to you. And if yes, please send me the swedish text for all these steps :)
1- item menu on the home page ("uppdatera min profil...")
2- pop-up when clicking on avboka
3- popup when unbooking processed
4- email to the admin
5- should we allow the users to see the 3rd block ? ("visa andra" with the list of sites)

**Comment by mathieuLU** [comment]
Ok so we have 2 alternatives : 

1- all the bookables sites can be unbooked, using the process described in the previous message

Missing in the previous list : when the user is about the unbook, a text field should be mandatory to specify the reason of the unbooking. This textfield will be pasted in the email sent to the admin (no need to save it in he database)

2- the same way that we have a flag "siteBooking" for the project with sites allowed to be booked, we could have a flag siteUnbooking to allow thhe unbooking only for these projects.

**Comment by mathieuLU** [comment]
Hej @fredrikhaas 

here is how it looks now  (TEST version)

homepage menu:
![Screenshot from 2023-07-12 17-03-28](https://github.com/biodiversitydata-se/biocollect/assets/50901365/956db26f-f6e7-4dd7-97b5-8a32d1c74606)

if admin, menu as usual : 
![Screenshot from 2023-07-12 17-02-43](https://github.com/biodiversitydata-se/biocollect/assets/50901365/5c1ee7fd-d364-4326-9ddb-f3fcd2f49078)

I kept the list the way it was, since it quite messy to change the order of the sites displayed. BUt I added the scheme column to help understanding

for normal users, only the unbookable sites have the unbook button : 
![Screenshot from 2023-07-12 17-02-32](https://github.com/biodiversitydata-se/biocollect/assets/50901365/9d06231d-a81f-4a67-b72f-2feca9218da9)

when clicking on unbook : 
![Screenshot from 2023-07-12 17-02-55](https://github.com/biodiversitydata-se/biocollect/assets/50901365/47b70e78-7c8c-4134-8543-89f8daf30e72)

the unbook information message
![Screenshot from 2023-07-12 17-09-06](https://github.com/biodiversitydata-se/biocollect/assets/50901365/174cdafb-f195-4799-943e-95d6936970b4)


Now I'm working on the email for the admin. 

Email: Subject - "Avbokning av IWC-lokal", Content: "Site/internal site ID har avbokats av Fredrik Haas, 650802-1", dvs "L016 har avbokats av Fredrik Haas, 650802-1"

**Comment by mathieuLU** [comment]
email is ready as well.
Can be deployed to production when you want!

**Comment by mathieuLU** [comment]
deployed in production.

works as well for Kustfågelrutor

email changed + email address fixed with https://github.com/biodiversitydata-se/biocollect/commit/cddc2daa868fab06270ca6e1141cc246cbe70e45 and https://github.com/biodiversitydata-se/biocollect/commit/fe837dec73dffdfdb794a2544899d1cc47bc49c0

allow to sort the table for a user like : 
![Screenshot from 2023-08-09 16-32-30](https://github.com/biodiversitydata-se/biocollect/assets/50901365/2c0a0bef-3692-43fc-ab9b-92500fc7a602)
with https://github.com/biodiversitydata-se/biocollect/commit/eaddd36b9d64cc181bb088356cb4305fff6f4304

I think it's all ok and can be closed now !

**Comment by fredrikhaas** [comment]
Looks good, fine with me to close the case.

Fredrik
