### ISSUE TITLE
Time stamps for Nattrutt

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#236]
When exporting data from Nattrutter I saw that there were several time stamps (the clock time for each point) that had errors, which were of two types:

1) Some hade more digits, up to 8 (e.g. "21122112" when it should have been "2112". 

I suggest a filter allowing maximum 4 digits.

2) For the hour between midnight (24.00/0.00) and 01.00 some have entered e.g. "2406" for 6 minutes past midnight. 

I suggest a filter not allowing values higher than 2359. Midnight should be 0 and not 2400, Six minutes past midnight should be 6 and not 2406. And so on.

**Comment by ekol-ali** [comment]
I have now gone through all time stamps and changed them according to the rule above. There were around 100-150 such errors. TWO errors remain that I couldn't edit, but they have an issue on their own (#237)

I changed the priority of this issue to HIGH, since a new nattrutt season just started and many make these mistakes when entering in BioCollect.

**Comment by mathieuLU** [comment]
done with https://github.com/Lund-University-Biodiversity-data/biocollect_forms/commit/2f5cfc00d25e7370be49fc044073cd41c8611967 !
looks like that : 
![Screenshot from 2023-03-06 10-36-13](https://user-images.githubusercontent.com/50901365/223072644-8852f34d-7249-448e-9f42-9517347282a6.png)

let me know if you think about other forms that would need that kind of filters
