### ISSUE TITLE
Fixed rotues - preventing filling in clocktime instead of minutes spent on the lines

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#242]
Many surveyors do not read the instructions properly... 
On the fixed routes they are suppossed to fill in how many minutes they spend  on counting per line. Some manage to fil in starttime instead.
Mathieu, can you for "species 000" and "L1...L8" put an upper limit of 120 to what can be put in these cells? Noone should survey at clock time 120 (01:20), and noone should spend more than 120 minutes on counting a line.
New fixed route surveys will start to be reported soon, so if done before 20 may would be fine... :-)

**Comment by mathieuLU** [comment]
you mean these ones right ?
![Screenshot from 2023-05-15 09-07-00](https://github.com/biodiversitydata-se/biocollect/assets/50901365/d9eecb0f-30cb-4a47-8703-4a80855d75e3)

**Comment by ekol-ali** [comment]
Yes!

**Comment by mathieuLU** [comment]
fixed 
![Screenshot from 2023-05-15 10-06-02](https://github.com/biodiversitydata-se/biocollect/assets/50901365/dc5ab2e0-4eaf-439c-bd9b-8a51c9fc2ed8)

**Comment by ekol-ali** [comment]
Great!
