### ISSUE TITLE
Highlighting the row when reporting

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#243]
Comment from Debora

`
I am reporting my numbers from my standradrutt, and I wonder:

 

When I write my numbers for a point or line, normally the cell that my curser is in is highlighted with a light blue frame.

Like this:

 

When I add a new species then all cells for the active pint or line (column) are filled yellow,

Like this:
![debora1](https://github.com/biodiversitydata-se/biocollect/assets/50901365/204f3b36-582e-42b7-98e1-41086f81d5c0)

but only until I save a draft, then all cells are white again.
![debora2](https://github.com/biodiversitydata-se/biocollect/assets/50901365/01100485-b43d-4990-aa71-c5c766f4701c)

 

I would find it very useful if always when I fill in a number for a point or line all cells of that point or line are highlighted, and additionally the row/line of the species I am filling the number in for. That way I can quickly see if I am in the correct column (point, number) and row (species), or whether I am by mistake put the cursor in the adjacent/wrong column or row. – I can see that now but I have to be much more alert.

I think this could help avoiding errors by filling in for the wrong point/line or species which are not easy to spot afterwards.

 

Of course I should find those mistakes when I check over all numbers before submitting. But my point is that it highlighting columns and rows would make data input a little easier and would help avoid such errors in the forst place.

 

Do you know if such highlighting could be made possble in the Biocollect application?
`

**Comment by mathieuLU** [comment]
done https://github.com/biodiversitydata-se/biocollect/commit/5d5ebf7cab189cdad9ea954838b38a1ee645e0d7

**Comment by DeboraArlt** [comment]
Nice!
Will be up for test in a few weeks ☺
