### ISSUE TITLE
Strange "AAUndersökning" in BioCollect

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#246]
https://biocollect.biodiversitydata.se/sft/person/edit/d6e03b11-454f-9a14-6165-014afb7a7ea7/?returnTo=/sft/project/index/89383d0f-9735-4fe7-8eb4-8b2e9e9b7b5c#activityList

There is a strange "AA" in front of "Undersökning" (på en av de tre flikarna högst upp). It is the same for all persons.

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biocollect/commit/eaea03bb7f8ffa323b0e9c82c47fb9b499183d67
