### ISSUE TITLE
Doubles in a summer point count entered via BioCollect

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#251]
To my great surprise I noticed today that some persons have managed to enter the same species twice or thrice when reporting a survey in BioCollect. I had thought (assumed) that was impossible. It is both in summer and winter point counts, and fixed routes (1).

https://biocollect.biodiversitydata.se/sft/bioActivity/index/1d518ebe-a660-43ff-b6eb-2fc5e73055ac
https://biocollect.biodiversitydata.se/sft/bioActivity/index/be197d87-d9da-4d9a-bfa6-835d9de0e2af
https://biocollect.biodiversitydata.se/sft/bioActivity/index/c46fbb27-1be0-40d0-8c08-aff3e0df4ad7
https://biocollect.biodiversitydata.se/sft/bioActivity/index/ec313638-a672-4038-accb-21ff5d5b410d
https://biocollect.biodiversitydata.se/sft/bioActivity/index/c11cb07c-0cb5-45f6-8c90-7b9172aa4cd1
https://biocollect.biodiversitydata.se/sft/bioActivity/index/ee57ab49-4ccd-498e-851e-3fc1863b255f

All of these have been entered directly in BioCollect, thus, they were not imported. Further, I did not change anything yet, so I need this list later to correct in the protocols.

This is really a bug (?) that must be fixed. Preferably very soon.

**Comment by mathieuLU** [comment]
sorry for the late answer
I investigated in the code. But it looks like it has been this way from the very beginning!
The users are asked to confirm or not if they want a duplicate or not, this way : 
![Screenshot from 2024-02-06 15-30-20](https://github.com/biodiversitydata-se/biocollect/assets/50901365/2fefae4a-f276-419a-93cc-819fdd10d199)

And if they accept, then we have the duplicate...
Of course I can remove the "confirm" question. And put an error message instead (which one ?) to force the user to change the line and edit the field.

**Comment by mathieuLU** [comment]
but do you have an idea why it has been decided this way first ?
really strange

**Comment by ekol-ali** [comment]
Hej igen,

pratade med Martin i annat ärende och vi diskuterade detta. Vi föreslår texten:

”Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det är inte tillåtet. Vänligen välj en annan art!”

Är det OK med dig Fredrik?

Åke




Från: mathieuLU ***@***.***>
Skickat: Tuesday, 6 February 2024 15:35
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


but do you have an idea why it has been decided this way first ?
really strange

**Comment by ekol-ali** [comment]
Hejsan,


föreslår följande lätta korrigering:


”Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det går inte att lägga till den här igen!”


Föreslår att vi tar bort orden om att välja annan art. Oftast (alltid?) ska väl uppgifterna som rapportören vill lägga in matas in på den art som redan finns (?). Jag tror alltså att det är få (inga?)) tillfällen när rapportören av misstag råkar skriva/välja fel art. Men visst, jag kan ha fel.


Bästa,


/Martin


Martin Green
Svensk Fågeltaxering
Ekologihuset
Lunds universitet
223 62 Lund
Tel. 046-2223816 Mobil: 0708-134975
http://www.fageltaxering.lu.se


________________________________
Från: Åke Lindström
Skickat: den 6 februari 2024 16:31
Till: biodiversitydata-se/biocollect
Kopia: Martin Green; Fredrik Haas
Ämne: Sv: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Hej igen,



pratade med Martin i annat ärende och vi diskuterade detta. Vi föreslår texten:



”Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det är inte tillåtet. Vänligen välj en annan art!”



Är det OK med dig Fredrik?



Åke









Från: mathieuLU ***@***.***>
Skickat: Tuesday, 6 February 2024 15:35
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)



but do you have an idea why it has been decided this way first ?
really strange

**Comment by ekol-ali** [comment]
Vare sig IWC eller kustrutorna får innehålla dubbletter så där bör texten fungera. I det senare protokollet registreras dock ejderungar i en egen sektion av protokollet och där blir det på sätt och vis en dubblett (i huvudsektionen där vuxna registreras/i sektionen för ejderungar).  Den dubbletten måste rent tekniskt tillåtas.

Fredrik

From: Åke Lindström
Sent: den 6 februari 2024 16:32
To: biodiversitydata-se/biocollect ***@***.***>
Cc: Martin Green ***@***.***>; Fredrik Haas ***@***.***>
Subject: Sv: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)

Hej igen,

pratade med Martin i annat ärende och vi diskuterade detta. Vi föreslår texten:

”Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det är inte tillåtet. Vänligen välj en annan art!”

Är det OK med dig Fredrik?

Åke




Från: mathieuLU ***@***.******@***.***>>
Skickat: Tuesday, 6 February 2024 15:35
Till: biodiversitydata-se/biocollect ***@***.******@***.***>>
Kopia: Åke Lindström ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


but do you have an idea why it has been decided this way first ?
really strange

**Comment by ekol-ali** [comment]
OK!
Åke

Från: Martin Green ***@***.***>
Skickat: Tuesday, 6 February 2024 16:36
Till: Åke Lindström ***@***.***>; biodiversitydata-se/biocollect ***@***.***>
Kopia: Fredrik Haas ***@***.***>
Ämne: SV: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Hejsan,



föreslår följande lätta korrigering:



"Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det går inte att lägga till den här igen!"



Föreslår att vi tar bort orden om att välja annan art. Oftast (alltid?) ska väl uppgifterna som rapportören vill lägga in matas in på den art som redan finns (?). Jag tror alltså att det är få (inga?)) tillfällen när rapportören av misstag råkar skriva/välja fel art. Men visst, jag kan ha fel.



Bästa,



/Martin


Martin Green
Svensk Fågeltaxering
Ekologihuset
Lunds universitet
223 62 Lund
Tel. 046-2223816 Mobil: 0708-134975
http://www.fageltaxering.lu.se

________________________________
Från: Åke Lindström
Skickat: den 6 februari 2024 16:31
Till: biodiversitydata-se/biocollect
Kopia: Martin Green; Fredrik Haas
Ämne: Sv: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Hej igen,



pratade med Martin i annat ärende och vi diskuterade detta. Vi föreslår texten:



"Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det är inte tillåtet. Vänligen välj en annan art!"



Är det OK med dig Fredrik?



Åke









Från: mathieuLU ***@***.******@***.***>>
Skickat: Tuesday, 6 February 2024 15:35
Till: biodiversitydata-se/biocollect ***@***.******@***.***>>
Kopia: Åke Lindström ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)



but do you have an idea why it has been decided this way first ?
really strange

-

**Comment by ekol-ali** [comment]
Precis!


Därav är ordet "sektion" av betydelse 😊


Exakt på samma sätt för nattrutterna där en art kan finnas med två gånger (vuxna o kullar av ugglor, däggdjur på punkt och transportsträcka).


Fridens,


/Martin


Martin Green
Svensk Fågeltaxering
Ekologihuset
Lunds universitet
223 62 Lund
Tel. 046-2223816 Mobil: 0708-134975
http://www.fageltaxering.lu.se


________________________________
Från: Fredrik Haas
Skickat: den 6 februari 2024 16:45
Till: Åke Lindström; biodiversitydata-se/biocollect
Kopia: Martin Green
Ämne: RE: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Vare sig IWC eller kustrutorna får innehålla dubbletter så där bör texten fungera. I det senare protokollet registreras dock ejderungar i en egen sektion av protokollet och där blir det på sätt och vis en dubblett (i huvudsektionen där vuxna registreras/i sektionen för ejderungar).  Den dubbletten måste rent tekniskt tillåtas.



Fredrik



From: Åke Lindström
Sent: den 6 februari 2024 16:32
To: biodiversitydata-se/biocollect ***@***.***>
Cc: Martin Green ***@***.***>; Fredrik Haas ***@***.***>
Subject: Sv: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)



Hej igen,



pratade med Martin i annat ärende och vi diskuterade detta. Vi föreslår texten:



”Hoppsan, denna art finns redan inlagd i denna sektion av protokollet. Det är inte tillåtet. Vänligen välj en annan art!”



Är det OK med dig Fredrik?



Åke









Från: mathieuLU ***@***.******@***.***>>
Skickat: Tuesday, 6 February 2024 15:35
Till: biodiversitydata-se/biocollect ***@***.******@***.***>>
Kopia: Åke Lindström ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)



but do you have an idea why it has been decided this way first ?
really strange

**Comment by mathieuLU** [comment]
Fixed with https://github.com/biodiversitydata-se/ecodata-client-plugin/commit/eee6148653aa09a2d29291c69f10b0ac24743a5c

looks like that : 
![Screenshot from 2024-02-07 17-43-24](https://github.com/biodiversitydata-se/biocollect/assets/50901365/6a9daf42-12a8-4050-9acb-e68726562de0)

Actually maybe I should do it as well for the mammals/owls tables (in each of these, there should not be duplicates as well right ?).
but of course it's still possible to have the same species list in 2 different tables as explained by Fredrik.

**Comment by ekol-ali** [comment]
Hej Mathieu,

Toppen!

Jag föreslår att du gör det för ALLA sektioner i alla delprogram.

Åke

Från: mathieuLU ***@***.***>
Skickat: Wednesday, 7 February 2024 17:46
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Fixed with ***@***.***<https://github.com/biodiversitydata-se/ecodata-client-plugin/commit/eee6148653aa09a2d29291c69f10b0ac24743a5c>

looks like that :
Screenshot.from.2024-02-07.17-43-24.png (view on web)<https://github.com/biodiversitydata-se/biocollect/assets/50901365/6a9daf42-12a8-4050-9acb-e68726562de0>

Actually maybe I should do it as well for the mammals/owls tables (in each of these, there should not be duplicates as well right ?).
but of course it's still possible to have the same species list in 2 different tables as explained by Fredrik.

**Comment by ekol-ali** [comment]
Halloj,


utmärkt och jag håller helt med Åke. Bör finnas i alla sektioner i alla delprogram!


Kör på!


/Martin


Svensk Fågeltaxering
Ekologihuset
Lunds universitet
223 62 Lund
Tel. 046-2223816 (Martin Green  & Fredrik Haas)
http://www.fageltaxering.lu.se



________________________________
Från: Åke Lindström
Skickat: den 8 februari 2024 08:44
Till: biodiversitydata-se/biocollect
Kopia: BIOL - Fågeltaxering
Ämne: Sv: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Hej Mathieu,



Toppen!



Jag föreslår att du gör det för ALLA sektioner i alla delprogram.



Åke



Från: mathieuLU ***@***.***>
Skickat: Wednesday, 7 February 2024 17:46
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)



Fixed with ***@***.***<https://github.com/biodiversitydata-se/ecodata-client-plugin/commit/eee6148653aa09a2d29291c69f10b0ac24743a5c>

looks like that :
Screenshot.from.2024-02-07.17-43-24.png (view on web)<https://github.com/biodiversitydata-se/biocollect/assets/50901365/6a9daf42-12a8-4050-9acb-e68726562de0>

Actually maybe I should do it as well for the mammals/owls tables (in each of these, there should not be duplicates as well right ?).
but of course it's still possible to have the same species list in 2 different tables as explained by Fredrik.

**Comment by mathieuLU** [comment]
Now the control is made in every section => https://github.com/biodiversitydata-se/ecodata-client-plugin/commit/3a02e4eb26de08442051b13da3b59c016cb65fad. And i have added the yellow highlightning everywhere as well => https://github.com/biodiversitydata-se/biocollect/commit/5d5ebf7cab189cdad9ea954838b38a1ee645e0d7

![Screenshot from 2024-02-14 14-53-33](https://github.com/biodiversitydata-se/biocollect/assets/50901365/8598ebbe-559c-4419-8024-e9071e4e269f)

@ekol-ali @fredrikhaas Please close the issue if you think it's solved !

**Comment by ekol-ali** [comment]
Strålande!
Tack!
Åke

Från: mathieuLU ***@***.***>
Skickat: Wednesday, 14 February 2024 14:56
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Mention ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Doubles in a summer point count entered via BioCollect (Issue #251)


Now the control is made in every section => ***@***.***<https://github.com/biodiversitydata-se/ecodata-client-plugin/commit/3a02e4eb26de08442051b13da3b59c016cb65fad>. And i have added the yellow highlightning everywhere as well => 5d5ebf7<https://github.com/biodiversitydata-se/biocollect/commit/5d5ebf7cab189cdad9ea954838b38a1ee645e0d7>

Screenshot.from.2024-02-14.14-53-33.png (view on web)<https://github.com/biodiversitydata-se/biocollect/assets/50901365/8598ebbe-559c-4419-8024-e9071e4e269f>

@ekol-ali<https://github.com/ekol-ali> @fredrikhaas<https://github.com/fredrikhaas> Please close the issue if you think it's solved !
