### ISSUE TITLE
For Kustfåglar surveys, the total column is not automatically edited when changing the values in ö/vatten

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#255]
the total column is supposed to bu automatically updated when changing the values in ö/vatten for the delprogram KustFåglar
https://biocollect.biodiversitydata.se/sft/bioActivity/edit/c937eb4b-9445-4e6d-a49a-509fb159722c
![Screenshot from 2024-08-27 16-19-12](https://github.com/user-attachments/assets/ff62f0b1-980a-4a48-bfad-1b012a2ad377)

it works in the creation mode without problem (one should set first the field "Jag har i kolumnen "Total" lagt in summerade värden" to "nej"

so the problem in the edit comes certainly from that extra field. Adding a field in the edit mode works for the automatic edit of the total column, but only for the extra line

**Comment by mathieuLU** [comment]
so far i can't make it

this field total is ruled by 2 properties:
 - defaultValue : that allows to get the sum only for the new rows
 - computed : that can help having the sum of water+island for the column total BUT it forces the cell to stay disabled/readonly the whole time (even when we switch to "Jag har i kolumnen "Total" lagt in summerade värden" = JA)

i keep searching...

**Comment by mathieuLU** [comment]
I found a way !!
![Screenshot from 2024-08-30 11-19-03](https://github.com/user-attachments/assets/67c164ce-da75-4b41-ae8d-b31e4027b85b)

kan du kolla @fredrikhaas  om det ser bra ut för dig ?

**Comment by mathieuLU** [comment]
bara säget till om du vill byta meddelandet eller ngt annat

**Comment by fredrikhaas** [comment]
Hej!
Om meddelande behövs så kan det kanske stå så här: ”Fälten överensstämmer inte (ö+vatten SKA vara lika med total).
Men när ska detta meddelande visas? Tanken är väl att det ska bli korrekt?

/Fredrik

**Comment by mathieuLU** [comment]
i switch to english for the record ;-)

you can try in BioCollect. The thing is that i cannot automate this total field to be all the time the sum of the other 2. Because some time one picks "Jag har i kolumnen "Total" lagt in summerade värden = JA" and then the sum function can't work anymore.

The form renderer makes everything less flexible for these customized controls. 
The only option i found is to check the total when "Jag har i kolumnen "Total" lagt in summerade värden = JA". At that moment only the check is done, and you get the error messages above the line(s) that is/are problematic

Please try in BioCollect to see if it suits you. I fix the message

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biocollect/commit/6212b6d79062a1d53554f46132ca4ba2a8bf5651 and https://github.com/biodiversitydata-se/biocollect/commit/67ce4044c184fdf37d8ef1015927400b6d382c50
