### ISSUE TITLE
Activate permission level: volunteer

### ISSUE THREAD

**Issue by larspett** [biodiversitydata-se/biocollect#46]
Volunteer would be "Fjärilsövervakare" and their permission levels should be set so they can view their site, add data, add sites, maybe be granted site edit rights. Please check any particular permission levels with me and I will try to answer promptly.

**Comment by larspett** [comment]
![image](https://user-images.githubusercontent.com/19598308/96440290-0ce05980-1208-11eb-8c18-3b39ffe49aee.png)

Am unsure what the differerence between Moderator and Redaktör is but project participant is not there currently anyway

**Comment by magdziarek** [comment]
I cannot see any good reason for the lack of project participant there, must be a bug, I will fix it. However, until I deploy a new version, you can still change the role to project participant underneath, in the table showing a list of users with their roles. In that dropdown all roles are available. Role in BioCollect are the following:
1. Administrator –This role is very powerful and gives holders full access and editorial rights to all aspects of the project, including editing of project and survey metadata pages, editing of any record within project surveys, ability to create and edit survey configurations, ability to add and edit blog items and resource items, add and edit project members and their permissions, etc. The person who creates a project is automatically assigned as an Administrator of the project. There can be multiple administrators. 
2. Editor – This is a dedicated member role which provides READ access to all aspects of the project and EDIT access only to data records which they create/submit themselves. The role does not have edit access to other contributor records, not any other aspect of the project. For systematic monitoring this will also include the option of creating a new site that has to be approved by the admin of the project.
3. Project participant – This role is essentially an honorary project member role for the purpose of data record entry only and is automatically assigned to public (non-member) contributors to the project (i.e. When the public participation checkbox is ticked in the step 1 survey configuration page). Permissions for this role are effectively the same as those for EDITOR.


I think as we are building a generic system for different organisms, we should stay away from very specific terms like "Fjärilsövervakare", especially that it is visible only to the admin. We can put it in the entry form for the volunteer where they enter their name, if you like.

**Comment by larspett** [comment]
Ok. As for the roles, I will look over the needs and provide feedback. When it comes to personalised terms like fjärilsövervakare, I think it would be extremely important to be able to pitch them to the actual scheme to make it more personal. Many volunteers are initially reluctant to use sites like this and either too formal or too informal (like parts of the start screen) language will work against the general use of the site. I suggest we use a skin-ish approach where parts of the content is possible to adapt to the particular audience. I.e. alternative hub-specific wording for selected words & phrases. That could still fit within a generic system. /Lars

19 okt. 2020 kl. 14:13 skrev magdziarek <notifications@github.com>:

﻿

I cannot see any good reason for the lack of project participant there, must be a bug, I will fix it. However, until I deploy a new version, you can still change the role to project participant underneath, in the table showing a list of users with their roles. In that dropdown all roles are available. Role in BioCollect are the following:

  1.  Administrator –This role is very powerful and gives holders full access and editorial rights to all aspects of the project, including editing of project and survey metadata pages, editing of any record within project surveys, ability to create and edit survey configurations, ability to add and edit blog items and resource items, add and edit project members and their permissions, etc. The person who creates a project is automatically assigned as an Administrator of the project. There can be multiple administrators.
  2.  Editor – This is a dedicated member role which provides READ access to all aspects of the project and EDIT access only to data records which they create/submit themselves. The role does not have edit access to other contributor records, not any other aspect of the project. For systematic monitoring this will also include the option of creating a new site that has to be approved by the admin of the project.
  3.  Project participant – This role is essentially an honorary project member role for the purpose of data record entry only and is automatically assigned to public (non-member) contributors to the project (i.e. When the public participation checkbox is ticked in the step 1 survey configuration page). Permissions for this role are effectively the same as those for EDITOR.

I think as we are building a generic system for different organisms, we should stay away from very specific terms like "Fjärilsövervakare", especially that it is visible only to the admin. We can put it in the entry form for the volunteer where they enter their name, if you like.
