### ISSUE TITLE
Top menu issues - logout button and sites

### ISSUE THREAD

**Issue by larspett** [biodiversitydata-se/biocollect#47]
- "Sites" on home screen redirects to SFT instead of sebms
- "Logout" is misaligned because of the associated icon

**Comment by magdziarek** [comment]
- "Sites" contains both SFT and SeBMS sites because it shows the sites on hub level - when we have two hubs this won't be an issue. You can filter them using the categories in the left hand menu.

**Comment by larspett** [comment]
Still, the list up there has no obvious meaning to me. Every menu should be well motivated and logical and listing sites (which will be more than 1000 even for just sebms) just because they can be listed is rather confusing. This looks like something inherited from the AUS Biocollect? We should design the access to different features of the database in a consistent way which is based on the user type an permission levels. I am happy to help tweaking the UX to achieve this. /Lars



Skickat från min iPad

19 okt. 2020 kl. 14:16 skrev magdziarek <notifications@github.com>:

﻿

  *   "Sites" contains both SFT and SeBMS sites because it shows the sites on hub level - when we have two hubs this won't be an issue. You can filter them using the categories in the left hand menu.

**Comment by magdziarek** [comment]
Agreed. And SFT never wanted it either. "Sites" are gone now from the top menu.

**Comment by magdziarek** [comment]
Logout translated and icon aligned
