### ISSUE TITLE
Change view of point sites from point to polygon

### ISSUE THREAD

**Issue by larspett** [biodiversitydata-se/biocollect#55]
All point sites are now available as polygons in the sebms database (public..geo_geometry) and should be shown as polygons instead of centroid midpoints in Biocollect. This will allow editing of point site outlines too.

**Comment by larspett** [comment]
You got both the sites and the persons who use these sites and who should be granted access to them

both files are UTF-8 csv files

[spatial_data_sebms.txt](https://github.com/biodiversitydata-se/biocollect/files/5422056/spatial_data_sebms.txt)
[persons_at_sites_sebms.txt](https://github.com/biodiversitydata-se/biocollect/files/5422061/persons_at_sites_sebms.txt)

**Comment by larspett** [comment]
Here is the sql for the extraction

[spatial_extraction.txt](https://github.com/biodiversitydata-se/biocollect/files/5422069/spatial_extraction.txt)

**Comment by magdziarek** [comment]
A slightly modified version of the sql query to get coordinates of segments as string in epsg 4326

[spatial_extraction_4326.txt](https://github.com/biodiversitydata-se/biocollect/files/5422321/spatial_extraction_4326.txt)

**Comment by larspett** [comment]
now as geojson 4326
[spatial_data_geojson_sebms.txt](https://github.com/biodiversitydata-se/biocollect/files/5422431/spatial_data_geojson_sebms.txt)
[spatial_extraction.txt](https://github.com/biodiversitydata-se/biocollect/files/5422433/spatial_extraction.txt)

**Comment by larspett** [comment]
aha so you did the same :) I did geojsons from them, thought that would be useful

**Comment by magdziarek** [comment]
@larspett After we looked at Lyftvägen 39 I just now realized the meaning of the title of this issue. At the moment, we have punktlokal and slinga - punktlokal contains all sites that I converted from shapefiles some weeks ago that have only one point each site. But you actually want all points changed into a polygon that is a buffer around the point - is this correct? 
Compare: 
A/ https://biocollect.bioatlas.se/lusm/site/index/bb3599a5-0907-464d-b101-bb42fd5cfb76 - incorrect?
![image](https://user-images.githubusercontent.com/26426498/97184286-0bcaa180-179f-11eb-8ff4-8c6a8668c153.png)

and
B/ https://biocollect.bioatlas.se/lusm/site/index/602b14a3-6450-480b-a98f-66d8241340b7 - correct?
![image](https://user-images.githubusercontent.com/26426498/97184253-01a8a300-179f-11eb-9546-38821e5f841f.png)

If yes, then I have questions:
1. Maybe we should store them as circular polygons, not multilines with many vertices? They would be displayed in a nicer way and store fewer coordinates.
2. I think you explained that point sites are not really point sites but just a transition stage into a transect. So you would like to see the point+circular buffer around it but the user who is the owner would then edit the circle into a transect (lines) and ultimately this transect would be stored as well.
3. If the latter is true, then would we have only one scheme "Slinga" and all sites should belong to that?

**Comment by larspett** [comment]
The answer to the first question is yes, 
For the followups
1. It depends on whether people will want to redraw them (which is likely). I can imagine someone wanting to tweak the boundaries and then it would become a polygon rather than a circlular polygon. To keep it general, I would imagine circles with fewer segments would be better (e.g. 36 rather than 360 or whatever)
2 no that is only speaking figuratively, you could view the point site as a one-segment transect with a peculiar shape but that is only in terms of analysis. Volunteers would never consider it like that
3 no I think we should keep them separate
