### ISSUE TITLE
automated record validation

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#57]
automated record validation during record entry for volunteers and during validation by admins. This will be a big task involving preparing the rules for this (geographic, temporal and likely number of individuals per species?)

**Comment by larspett** [comment]
Here is an example of how this can be done, three fields with separate validation rules with reference data brought from spv_speciesvalidation. One is rarity (or difficulty to identify) within a region, one is flighttime (before or after normal flight time) and one is rare (or difficult) species in the Swedish mountains ping @magdziarek @mathieuLU 
[observations_2019_with_validation.txt](https://github.com/biodiversitydata-se/biocollect/files/5455131/observations_2019_with_validation.txt)

**Comment by larspett** [comment]
These rules are hardcoded but could also be as shapefiles etc (but hardcoded rules work quite fine, although the flight time is a bit too conservative)

**Comment by larspett** [comment]
a small tweak replacing the flag "1" with the amount of weeks before or after the flighttime window in the flighttime_validation column and sorting on the abs( ) value of it

[observations_2019_with_validation_2.txt](https://github.com/biodiversitydata-se/biocollect/files/5455997/observations_2019_with_validation_2.txt)

**Comment by magdziarek** [comment]
Thanks, looks good at first sight but I will keep the details for after the test launch.
