### ISSUE TITLE
change colours of features on maps 

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#66]
Lars's suggestions: 
`color = "#d0f01d", 
                weight = 1,
                smoothFactor = 0.5,
                opacity = 1.0,
                fillOpacity = 0.5,
                highlight = highlightOptions(color = "white", weight = 2,bringToFront = TRUE),`

**Comment by magdziarek** [comment]
@larspett I checked with the styling you suggested but it's still quite bleak, and the white highlight resembles roads too much on other base maps than satellite. 
![bild](https://user-images.githubusercontent.com/26426498/98096695-5c6f8800-1e8c-11eb-9dad-8769de5e40d8.png)
Higher opacity helps a bit but still it's a bit too close to green on green areas 
![bild](https://user-images.githubusercontent.com/26426498/98099092-6f378c00-1e8f-11eb-9c96-f453cf04191e.png)

![bild](https://user-images.githubusercontent.com/26426498/98098921-3dbec080-1e8f-11eb-9289-0d68d7dab1c1.png)

I would opt for something that is visible on all backgrounds like orange/ red (in the image it's #e82222) with high opacity. e.g. 0.8 maybe. But not being a graphic designer I am also tempted to trust the default blue-ish colour but with higher opacity.  
![bild](https://user-images.githubusercontent.com/26426498/98098077-26cb9e80-1e8e-11eb-930b-e82a4c12b5af.png)
![bild](https://user-images.githubusercontent.com/26426498/98098228-5aa6c400-1e8e-11eb-8747-22a933993a33.png)
We could make the colour specific to the layer but that would require a lot of work so cannot be done any time soon. 

Let's compromise on a colour that looks good against all base maps for now.

**Comment by larspett** [comment]
OK plz choose some version that fits better with visibility requirements
