### ISSUE TITLE
Editing a record creates a duplicate

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#68]
Strange behaviour : when I edit an existing record, it recreates it in the database
https://biocollect.bioatlas.se/lusm/bioActivity/index/0e8f3526-49da-409b-9271-b3bffd41ed29
I created it once (3 records, 1 output). Then I edit it, and now I have
6 records (and still 1 output which is ok)

**Comment by magdziarek** [comment]
This is due to the audit - when a record is updated the original gets status "deleted" and a new one is created
