### ISSUE TITLE
Activity 

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#84]
Please add a field called "verificationStatus" with the value of "not confirmed" when creating a new activity from an xls file
This field is a string of any one of the following values:
- not approved 
- not applicable
- under review
- approved
- 
eg. new format of document in activity collection:

```
db.activity.find({activityId: "12c65067-0f63-4f24-98d9-5ff2751836f4"}).pretty()
{
	"_id" : ObjectId("5fe9ea63f14cc247d51fb141"),
	"activityId" : "12c65067-0f63-4f24-98d9-5ff2751836f4",
	"assessment" : false,
	"dateCreated" : ISODate("2020-12-28T14:23:31.311Z"),
	"lastUpdated" : ISODate("2021-01-11T20:03:02.942Z"),
	"progress" : "planned",
	"projectActivityId" : "ccace44f-c37a-44de-a586-7880128046d3",
	"projectId" : "b7eee643-d5fe-465e-af38-36b217440bd2",
	"projectStage" : "",
	"siteId" : "59c6ed58-c4e3-4310-8a5f-64536551986c",
	"status" : "active",
	"type" : "Vinterrutt",
	"userId" : "6",
	"mainTheme" : "",
	"personId" : "ec390109-e002-4b61-a058-c6e09506cad6",
	"verificationStatus" : "not verified"
}
```

**Comment by magdziarek** [comment]
Confirmed

**Comment by mathieuLU** [comment]
Done ! Before I close it, do you want me to add this field as well for the historical data ?
Like : "verificationStatus" : "approved"

Or maybe it's better to have nothing for the rows that did not go through this verification process ?
you tell me

**Comment by magdziarek** [comment]
Thanks! You can't leave it null nor not have the field. I'd say make all SFT historical data approved because they were presumably approved.

**Comment by mathieuLU** [comment]
ok so 
=> "verificationStatus" : "approved"
for all historical SFT data

what about SEBMS ?

**Comment by magdziarek** [comment]
Yes. 
SeBMS...they haven't decided whether they would use this feature. Please assign "verificationStatus" : "not applicable"

**Comment by mathieuLU** [comment]
Done. I close
