### ISSUE TITLE
When importing surveys from xls...

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#85]
assign a value of verificationStatus to Activity dependent on projectActivity.adminVerification

`if (projectActivity.adminVerification){

// assign a value of 1, the equivalent of "not verified"
verificationStatus = 1

} else {

// assign 0 the equivalent of "not applicable"
verificationStatus = 0
}
`

**Comment by mathieuLU** [comment]
I guess this one is outdated right ?

**Comment by magdziarek** [comment]
True!
