### ISSUE TITLE
When exporting records to a csv file....

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#86]
exclude activities that have recordVerification == "approved" (the ones that have gone through a verification process) or "not applicable" (don't have to go through verification process)

**Comment by mathieuLU** [comment]
So I guess I will only export when activity has a verificationsStatus = Approved, right ?

**Comment by magdziarek** [comment]
I would say yes, but I will double check tomorrow with Martin and Fredrik.
