### ISSUE TITLE
Create person: Validate format of date, postal code, etc

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#94]
Validate format of: postal codes and year of birth, etc

**Comment by larspett** [comment]
year of birth can be four digit. Postal code is kept as XXX XX now in the database but supplied formats could be XXXXX or SE-XXX XX or SE-XXXXX (for Sweden, we do have volunteers from Denmark etc too with different formatting so coming to think of it, requiring a postal code format will cause errors.) Not sure what to do about that,

**Comment by larspett** [comment]
Here are the cases with length >6 (there are plenty of NULL too)

![image](https://user-images.githubusercontent.com/19598308/109157754-c16c2800-7772-11eb-975e-397f064261e4.png)

**Comment by magdziarek** [comment]
Can we leave the post code without verification then, assuming it won't cause big issues if the volunteer introduces an incorrect post code? I.e. you don't send them much post.
I will add a check on the year format

**Comment by larspett** [comment]
Yes

25 feb. 2021 kl. 14:49 skrev magdziarek <notifications@github.com>:

﻿

Can we leave the post code without verification then, assuming it won't cause big issues if the volunteer introduces an incorrect post code? I.e. you don't send them much post.
I will add a check on the year format
