### ISSUE TITLE
Person collection

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#96]
**projects**
needs to have project ids of all projects in the hub the person is using  - persons get assigned to a hub rather than individual projects. 
so for SFT
`person.projects = ["89383d0f-9735-4fe7-8eb4-8b2e9e9b7b5c", "d0b2f329-c394-464b-b5ab-e1e205585a7c", "b7eee643-d5fe-465e-af38-36b217440bd2", "49f55dc1-a63a-4ebf-962b-4d486db0ab16"]`
and for SeBMS:
`person.projects = ["1fb10915-e6c0-451e-b575-b7e715d5d32f", "30634be4-7aac-4ffb-8e5f-5e100ed2a4ea"]`

**internalPersonId**
is still a mandatory field, migrate as is personnummer in postgres

If there are sites that the person has created an surveys every year without the need to book, e.g. for vinterrutt, their ids go into 
ownedSites which is an array of strings, e.g.
`"ownedSites" : [
		"c2b0e083-28de-4a21-a150-030a5caa1280"
	]`
-> IMPORTANT - in this case the site should also have the person's ID as a string in the field called "owner"

If a person has booked sites then their ids go inside "bookedSites" field which is an array of strings, e.g.:
`"bookedSites" : [
		"83c3c0e7-ea64-4626-9d6d-e47e31cac759",
		"bd30e781-4d6b-426f-a1ee-f96a08c77337"
	]`

**Comment by mathieuLU** [comment]
OK for the person.projects field
internalPersonId is OK as well

regarding the ownedSites:
I understand the logic BUT the owner of a site is not stored in the SFT  database. Except if I consider that the 1st surveyor of a nattrutt site is its creator?
Do we have to  fill this field for historical data ?
If yes, maybe I should contact SFT people to see what kind of algorithm we should implement

**Comment by magdziarek** [comment]
It should be the first surveyor for all the sites that don't require booking but were created by the surveyor. But best to contact SFT people to double check. I will send them an email now.

**Comment by magdziarek** [comment]
When migrating persons add a field called "hub" with a value type String corresponding to the name of the hub they will belong to, "sft" or "sebms". 
`"hub": "sft"`
